apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-demo-configmap
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: test-vol
      mountPath: /etc/config-map-data
      readOnly: true
  volumes:
    - name: test-vol
      configMap:
        name: demo-configmap
        items:
        - key: test_file1.txt
          path: test_file1.txt
        - key: test_file2.txt
          path: test_file2.txt