apiVersion: v1
kind: Service	
metadata:
  name: nodeport-service
  labels:
    app: test-nodeport
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
  - nodePort: 31111
    port: 80
    targetPort: 80